force-app/main/default/objects/Airline__c/Airline__c.object-meta.xml
<CustomObject>
    <label>Airline</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Airline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airlines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airline__c/fields/IATA__c.field-meta.xml
<CustomField>
    <fullName>IATA__c</fullName>
    <label>IATA</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Airport Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/IATA__c.field-meta.xml
<CustomField>
    <fullName>IATA__c</fullName>
    <label>IATA</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AmountOfTravellers__c.field-meta.xml
<CustomField>
    <fullName>AmountOfTravellers__c</fullName>
    <label>AmountOfTravellers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TravelEndDate__c.field-meta.xml
<CustomField>
    <fullName>TravelEndDate__c</fullName>
    <label>Travel End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TravelStartDate__c.field-meta.xml
<CustomField>
    <fullName>TravelStartDate__c</fullName>
    <label>Travel Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FlightSearchDataSeeder.cls
public with sharing class FlightSearchDataSeeder {
  public static void createAirports(){
    Map<String, String> airports = FlightSearchApi.airports;
    List<Airport__c> airportRecords = new List<Airport__c>();
    for(String code : airports.keySet()){
      airportRecords.add(new Airport__c( IATA__c = code, DisplayName__c = airports.get(code)));
    }
    insert airportRecords;
  }

  public static void createAirlines(){
    Map<String, String> airlines = FlightSearchApi.airlines;
    List<Airline__c> airlineRecords = new List<Airline__c>();
    for(String code : airlines.keySet()){
      airlineRecords.add(new Airline__c( IATA__c = code, DisplayName__c = airlines.get(code)));
    }
    insert airlineRecords;
  }

  public static void createOpportunity(){
    Opportunity opp = new Opportunity(
            Name = 'Test Flight Booking',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            TravelStartDate__c = Date.today().addDays(10),
            TravelEndDate__c = Date.today().addDays(22),
            AmountOfTravellers__c = Math.floor(Math.random() * 5) + 1

    );
    insert opp;
  }

  public static void seedData(){
    createAirports();
    createAirlines();
    createOpportunity();
  }
}